### ISSUE TITLE
No need to wait after Wire.requestFrom()

### ISSUE THREAD

**Issue by Koepel** [TOLDOTECHNIK/TTSi7006#1]
In the file "TTSi7006.cpp" there is a while-loop after Wire.requestFrom() in two places. You can remove those while-loops. There is nothing to wait for. The delay(1), the retries, and polling Wire.available() are not needed.

When the Wire.requestFrom() returns, the I2C transactions has completely finished. The received data is in a buffer in the Wire library. The Wire.available() tells how many bytes are in that buffer. When two bytes are requested then Wire.available() returns two when the I2C transaction was successful, and probably zero when there was a I2C bus error.

**Comment by TOLDOTECHNIK** [comment]
Thank you for this input. You're right, delay is not needed in this case. We just changed the code.
