### ISSUE TITLE
can't make it work :(

### ISSUE THREAD

**Issue by jnrivra** [TOLDOTECHNIK/TTSi7006#3]
Hello everyone!

I'm doing a small project with the Si7006 and if i use an i2C scanner i can read the 0x40 address but with different libraries and examples codes i cant get the sensor to give the correct values.

any ideas? tried with 4 different boards

1384, room 16 
tail 8
chksum Si7006 is connected: No
Humidity: -6.00 % rel.
Temperature: 0.00 ⸮C
Temperature: 32.00 ⸮F

**Comment by TOLDOTECHNIK** [comment]
Hi,

Could you please try to run this code? This is the core to read out the temperature:
```
#include <Wire.h>

#define TTSi7006_I2C_ADDRESS 0x40
#define TTSi7006_REG_TEMP 0xE3

void setup() {
  Wire.begin();
  Serial.begin(9600);
}

void loop() {
  float temperature = 0;
  Wire.beginTransmission(TTSi7006_I2C_ADDRESS);
  Wire.write(TTSi7006_REG_TEMP);
  Wire.endTransmission();
  Wire.requestFrom(TTSi7006_I2C_ADDRESS, (byte)2);

  if (Wire.available() > 1) {
    temperature = Wire.read() * 256.0 + Wire.read();
    temperature = ((175.72 * temperature) / 65536.0) - 46.85;
  }

  Serial.println(temperature);
  delay(1000);
}
```

**Comment by jnrivra** [comment]
Hi there, than you so much for your help! unfortunately it doesn't work, this is what happens:

1. this is the schematic of the board:
<img width="707" alt="captura de pantalla 2019-02-27 a la s 15 00 10" src="https://user-images.githubusercontent.com/1253028/53512001-6da1a800-3aa0-11e9-93bc-d281428904f2.png">

2. when i run the i2c scanner i get this:
<img width="1680" alt="captura de pantalla 2019-02-27 a la s 14 41 05" src="https://user-images.githubusercontent.com/1253028/53512022-7f834b00-3aa0-11e9-97d8-ad9d785fe2ef.png">

3. and your code gives me back this:
<img width="1680" alt="captura de pantalla 2019-02-27 a la s 14 42 02" src="https://user-images.githubusercontent.com/1253028/53512051-945fde80-3aa0-11e9-8fbc-22166fc72860.png">

4. and i forced the scl and sda but no luck:
<img width="1680" alt="captura de pantalla 2019-02-27 a la s 14 51 07" src="https://user-images.githubusercontent.com/1253028/53512064-9e81dd00-3aa0-11e9-8f6c-0c1ad840aa3d.png">


i have 5 boards with the same problem and i can read other i2c sensors, i even desoldered everything and just put the esp12 with the sensor and no luck also, i tried with 4.7k and 10k pullup for the i2c

thanks!

**Comment by TOLDOTECHNIK** [comment]
It's not very clear: Do you try to run the sketch on an ESP8266? We didn't test the library on this chip.

Did you already try this library? https://github.com/automote/Si7006

**Comment by jnrivra** [comment]
Oh, yes its an 8266, the problem was in fact the library as you pointed, this one worked like a charm:
https://github.com/ControlEverythingCommunity/SI7006-A20

thank you so much for your support!
Juan
